# Generated by Django 4.2.1 on 2023-10-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('child_image', models.ImageField(upload_to='child_image')),
            ],
        ),
    ]
