# Generated by Django 4.2.1 on 2023-10-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_child_birth_mark_child_child_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_height',
            field=models.IntegerField(default=None),
        ),
    ]
