# Generated by Django 4.2.1 on 2023-10-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_child_child_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lostchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('fir_no', models.CharField(max_length=100)),
                ('child_image', models.ImageField(upload_to='child_image')),
                ('birth_mark', models.CharField(default='none', max_length=100)),
                ('child_height', models.IntegerField(default=None)),
            ],
        ),
    ]
