# Generated by Django 4.2.1 on 2023-10-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lostchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostchild',
            name='description',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
